services:
  principal:
    build: './source'
    volumes:
      - ./source:/var/www
    env_file:
      - ./source/.env

  producto:
    restart: always
    build: './service/productos'

  usuario:
    restart: always
    build: './service/usuarios'
    env_file:
      - ./service/usuarios/.env

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - principal
      - producto
      - usuario