version: '3'

services:
  principal:
    build: './source'
    volumes:
      - ./source:/var/www

  producto:
    restart: always
    build: './service/productos'

  usuario:
    restart: always
    build: './service/usuarios'

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - principal
      - producto
      - usuario